//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated to restore strongly-typed resource access.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Drawing;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    [GeneratedCode("Manual", "1.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Bitmap Gym_Interior_Flat_Cartoon_Background_high_resolution_preview_1322676
        {
            get { return (Bitmap)ResourceManager.GetObject("Gym_Interior_Flat_Cartoon_Background_high_resolution_preview_1322676", resourceCulture); }
        }

        internal static Bitmap visibility_16dp_000000_FILL0_wght400_GRAD0_opsz20
        {
            get { return (Bitmap)ResourceManager.GetObject("visibility_16dp_000000_FILL0_wght400_GRAD0_opsz20", resourceCulture); }
        }

        internal static Bitmap visibility_off_16dp_000000_FILL0_wght400_GRAD0_opsz20
        {
            get { return (Bitmap)ResourceManager.GetObject("visibility_off_16dp_000000_FILL0_wght400_GRAD0_opsz20", resourceCulture); }
        }

        internal static Bitmap house_2933360
        {
            get { return (Bitmap)ResourceManager.GetObject("house_2933360", resourceCulture); }
        }

        internal static Bitmap businessman_11323168
        {
            get { return (Bitmap)ResourceManager.GetObject("businessman_11323168", resourceCulture); }
        }

        internal static Bitmap statistics_4197942
        {
            get { return (Bitmap)ResourceManager.GetObject("statistics_4197942", resourceCulture); }
        }

        internal static Bitmap schedule_10179060
        {
            get { return (Bitmap)ResourceManager.GetObject("schedule_10179060", resourceCulture); }
        }

        internal static Bitmap people_16419568
        {
            get { return (Bitmap)ResourceManager.GetObject("people_16419568", resourceCulture); }
        }

        internal static Bitmap business_15649327
        {
            get { return (Bitmap)ResourceManager.GetObject("business_15649327", resourceCulture); }
        }

        internal static Bitmap book_14739729
        {
            get { return (Bitmap)ResourceManager.GetObject("book_14739729", resourceCulture); }
        }

        internal static Bitmap money_4322197
        {
            get { return (Bitmap)ResourceManager.GetObject("money_4322197", resourceCulture); }
        }

        internal static Bitmap defaultUser
        {
            get { return (Bitmap)ResourceManager.GetObject("defaultUser", resourceCulture); }
        }
    }
}
